### PR TITLE
Publish externalized events to SQS and SNS

### LINKED ISSUE #344: Publish externalized events to AWS services
In addition to Kafka, AMQP and JMS, Modulith could publish externalized events to AWS services: SQS, SNS and perhaps Kinesis.

This can be implemented either here - using AWS SDK directly - or in [Spring Cloud AWS](https://github.com/awspring/spring-cloud-aws) where we could use Spring Cloud AWS infrastructure to configure AWS clients.

### PR DESCRIPTION
**Pull request by maciejwalkowiak**
Fixes #344.

### CODE REVIEW

**Comment by odrotbohm** [comment]
This generally looks good to me. Trying to run the tests, I see them failing with:

```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [software.amazon.awssdk.services.sqs.SqsAsyncClient]: Factory method 'sqsAsyncClient' threw exception with message: Unable to load region from any of the providers in the chain software.amazon.awssdk.regions.providers.DefaultAwsRegionProviderChain@36510e73: [software.amazon.awssdk.regions.providers.SystemSettingsRegionProvider@1abcd059: Unable to load region from system settings. Region must be specified either via environment variable (AWS_REGION) or  system property (aws.region)., software.amazon.awssdk.regions.providers.AwsProfileRegionProvider@4ae8fb2a: No region provided in profile: default, software.amazon.awssdk.regions.providers.InstanceProfileRegionProvider@113dcaf8: Unable to contact EC2 metadata service.]
```

I guess you have the missing setting already set up in your environment as you're dealing with SC AWS all the time?

**Comment by maciejwalkowiak** [comment]
You're right, forgot to set the region that got loaded on my machine from AWS configuration files. Now should be fine.

**Comment by odrotbohm** [comment]
Thanks for that! One final question and then I think we can even merge this for inclusion into the 1.1 RC2 release on Friday:

I am in the process of changing the return type of `DelegatingEventExternalizer.externalize(Object, RoutingTarget)` to `CompletableFuture` to smoother align with the async result processing of the framework, allow for better invocation of broker APIs exposing an async API in turn (Kafka, for example). It would also allow us to conclude the event externalization with an event publication signalling the result in turn.

It looks like for the SQS variant, the `SendResult` returned from the actual send operation would be exactly such a result. In the SNS world, no result exists, but you explicitly catch a `MessageDeliveryException` to log some output in case of a particular cause. Is there a specific reason for that? In a world of a `CompletableFuture` return values, I'd return such an exception as `….failedFuture(…)` directly so that it is eventually handled by the global exception handling set up for asynchronous method invocations. Do you think there'd be anything wrong with that?

**Comment by maciejwalkowiak** [comment]
In SNS integration `MessageDeliveryException` is caught just for the sake of logging as it is easy to miss the fact that SNS topic must have content deduplication enabled, and without this log it is unclear what's the cause. The exception is later on re-thrown. 

I suggest keeping this PR open and I'll adjust it once you change `DelegatingEventExternalizer.externalize` to return `CompletableFuture`. If that would work for you, just ping me here when that change is merged.

**Comment by odrotbohm** [comment]
I have the adapted flavor of your submission ready to be merged in [this branch](https://github.com/spring-projects/spring-modulith/tree/issue/344-aws-event-externalization). I've dropped the explicit logging as I think it should be fine if the exception propagates into the exception handler that would log the full exception anyway?

**Comment by maciejwalkowiak** [comment]
I must have missed that it gets logged. In such case perhaps there's no point in catching `MessagingException`?

**Comment by odrotbohm** [comment]
You're right. I've put a global catch for `RuntimeException` into `DelegatingEventExternalizer` to channel all exceptions occurring during externalization into a failed `CompletableFuture`. Unless there's any other objections, I'd merge this tomorrow then.

**Comment by odrotbohm** [comment]
That's merged now, thanks!

**Comment by vpavic** [comment]
FWIW, I don't think it's wise for this project to have a dependency on community managed library that itself depends on Spring Boot.

This opinion is based on the fact that it took around half a year for Spring Cloud AWS to publish a release that's compatible with Spring Boot 3.0. This is not meant to be a critique of Spring Cloud AWS, but rather a general observation about the state of affairs with community managed open-source libraries. If something like that happens again, it will be a blocker for new Spring Modulith releases, that would otherwise be possible shortly after Spring Boot does its own.

Alternatives are to either implement this directly against AWS SDK, or to have it as a part of Spring Cloud AWS itself.

**Comment by odrotbohm** [comment]
Has been on my radar already and will be taken care of going forward. Thanks!

**Pull request closed without merging**
