### PR TITLE
GH-15 Trigger database initialization on embedded ones by default

### LINKED ISSUE #15: Trigger database initialization on embedded ones by default

### PR DESCRIPTION
**Pull request by nkolosnjaji**
Done for jdbc module.

Mongo and JPA modules are already working out of the box.

Closes #15

### CODE REVIEW

**Review by odrotbohm — CHANGES_REQUESTED** [review]
Thanks for the submission, Nikola. There are a few things that are still needed:

- There already is an `EmbeddedDatabaseCondition` in Spring Boot. Unfortunately, it's package protected. I'll go ahead and request it being promoted to a top-level type so that we can reuse it. For now, I guess a copy of the source of it should do the trick. Ticked for reference: https://github.com/spring-projects/spring-boot/issues/33627
- The `WithInitDisabled` base class was completely removed. Looks like we didn't have any actual test classes that extend from that (doh!). It would be nice if we could have at least one setup for an embedded and non-embedded database, that verify the initializer does not get registered if disabled explicitly.
- Finally, the condition on `OnExplicitEnable`, shouldn't that have a `havingValue="true"` because we want to enable initialization on both-embedded databases, or for any database if explicitly opted in, right?

**Comment by nkolosnjaji** [comment]
@odrotbohm my tests are failing, but not sure why is that. 
For example "mysql init disabled" fails, if I add "debug: true" to mysql yaml files then I can see:

`Unconditional classes:
----------------------
    org.springframework.boot.test.autoconfigure.jdbc.TestDatabaseAutoConfiguration
    org.springframework.modulith.events.jdbc.JdbcEventPublicationAutoConfiguration`

It looks like conditional annotation was never evaluated:

`@Bean
@Conditional(DatabaseSchemaInitializerCondition.class)
DatabaseSchemaInitializer`

Not sure what I'm doing wrong here.

**Comment by nkolosnjaji** [comment]
Redone, added additional tests + classpath resource for _getSchemaResourceFilename_ in _DatabaseType_

**Comment by odrotbohm** [comment]
Thanks, Nikola. I'll have a look ASAP.

**Pull request closed without merging**
